"""Regression tests against the committed PyPhi oracle fixtures.

Every fixture in ``tests/oracle/fixtures/`` was generated by the pinned oracle
environment in ``tests/oracle/generate/`` (PyPhi ``main`` @ ``ce2b2832``, presets
``IIT_3_0`` and ``IIT_4_0_2023``) and is self-contained: network, conventions, and
results. These tests rebuild each system in iitx and compare.

Tolerances differ by theory version because the oracles round differently: IIT 4.0
values carry full float64 precision (compared at 1e-9); IIT 3.0 stores every φ rounded
to 1e-6 and transports the *rounded* masses in Φ, so its values inherit a few units of
1e-6 (compared at 5e-6).
"""

import json
import pathlib

import jax.numpy as jnp
import numpy as np
import pytest

from iitx.enumeration import subsets, system_cuts
from iitx.measures import iit3, iit4
from iitx.system import System

FIXTURES = pathlib.Path(__file__).parent / "fixtures"

ATOL_IIT3 = 5e-6
ATOL_IIT4 = 1e-9


def load(version: str, name: str) -> dict:
	"""Load one fixture.

	Args:
		version: ``iit3`` or ``iit4``.
		name: Fixture name.

	Returns:
		The parsed fixture.

	"""
	with (FIXTURES / version / f"{name}.json").open() as handle:
		return json.load(handle)


def build_system(fixture: dict) -> tuple[System, jnp.ndarray]:
	"""Rebuild a fixture's system and state.

	Args:
		fixture: The parsed fixture.

	Returns:
		The system and its current state.

	"""
	network = fixture["network"]
	system = System(
		tpm=jnp.asarray(network["tpm_state_by_state"], dtype=jnp.float64),
		shape=tuple(network["alphabet"]),
		cm=jnp.asarray(network["cm"], dtype=bool),
	)
	return system, jnp.asarray(network["state"])


def names(version: str) -> list:
	"""List fixture names of one theory version, marking slow ones.

	Args:
		version: ``iit3`` or ``iit4``.

	Returns:
		Pytest params, sorted by name.

	"""
	params = []
	for path in sorted((FIXTURES / version).glob("*.json")):
		if path.stem == "basic_mechanisms":
			continue
		fixture = json.loads(path.read_text())
		marks = [pytest.mark.slow] if fixture.get("slow") else []
		params.append(pytest.param(path.stem, marks=marks))
	return params


@pytest.mark.parametrize("name", names("iit4"))
def test_iit4_fixture(name: str) -> None:
	"""Test the full IIT 4.0 analysis against an oracle fixture."""
	fixture = load("iit4", name)
	system, state = build_system(fixture)
	results = fixture["results"]

	structure = iit4.phi_structure(system, state)

	assert float(structure.system.phi) == pytest.approx(results["phi_s"], abs=ATOL_IIT4)
	assert float(structure.system.normalized_phi) == pytest.approx(
		results["normalized_phi"], abs=ATOL_IIT4
	)
	if results["mip"] is not None:
		_, severed = system_cuts(system.n)
		assert int(severed[structure.system.cut_index]) == results["mip"]["num_connections_cut"]

	exists = np.asarray(structure.distinctions.exists)
	assert int(exists.sum()) == results["num_distinctions"]
	assert float(np.asarray(structure.distinctions.phi)[exists].sum()) == pytest.approx(
		results["sum_phi_d"], abs=ATOL_IIT4
	)
	assert int(structure.relations.count) == results["num_relations"]
	assert float(structure.relations.sum_phi) == pytest.approx(results["sum_phi_r"], abs=ATOL_IIT4)
	assert float(structure.big_phi) == pytest.approx(results["big_phi"], abs=ATOL_IIT4)


@pytest.mark.parametrize("name", names("iit3"))
def test_iit3_fixture(name: str) -> None:
	"""Test the full IIT 3.0 analysis against an oracle fixture."""
	fixture = load("iit3", name)
	system, state = build_system(fixture)
	results = fixture["results"]

	analysis = iit3.system_phi(system, state)

	assert float(analysis.phi) == pytest.approx(results["phi"], abs=ATOL_IIT3)

	exists = np.asarray(analysis.ces.exists)
	assert int(exists.sum()) == results["num_concepts"]
	assert float(np.asarray(analysis.ces.phi)[exists].sum()) == pytest.approx(
		results["sum_small_phi"], abs=ATOL_IIT3
	)

	by_mechanism = {
		tuple(int(u) for u in np.flatnonzero(np.asarray(analysis.ces.mechanism)[k])): k
		for k in np.flatnonzero(exists)
	}
	for concept in results["concepts"]:
		k = by_mechanism[tuple(concept["mechanism"])]
		assert float(analysis.ces.phi[k]) == pytest.approx(concept["phi"], abs=ATOL_IIT3)
		for direction, purview_field in (("cause", "cause_purview"), ("effect", "effect_purview")):
			purview = tuple(
				int(u) for u in np.flatnonzero(np.asarray(getattr(analysis.ces, purview_field))[k])
			)
			assert purview == tuple(concept[direction]["purview"])


def test_iit3_basic_mechanism_repertoires() -> None:
	"""Test every repertoire of the basic network against the oracle's micro-fixture.

	The most diagnostic comparison for a reimplementation: for every mechanism and
	purview, the cause and effect repertoires (over purview states, little-endian) and
	the unconstrained repertoires.
	"""
	from iitx.direction import Direction
	from iitx.repertoires import condition, repertoire
	from iitx.system import node_tpms

	fixture = load("iit3", "basic_mechanisms")
	system, state = build_system(fixture)
	factors = condition(node_tpms(system), state, jnp.ones(system.n, dtype=bool))

	def purview_marginal(full: jnp.ndarray, purview: tuple[int, ...]) -> np.ndarray:
		axes = tuple(axis for axis in range(system.n) if axis not in purview)
		return np.asarray(full.sum(axis=axes)).ravel(order="F")

	for entry in fixture["results"]["repertoires"]:
		purview = tuple(entry["purview"])
		purview_mask = jnp.zeros(system.n, dtype=bool).at[jnp.asarray(purview)].set(True)
		empty = jnp.zeros(system.n, dtype=bool)

		np.testing.assert_allclose(
			purview_marginal(
				repertoire(factors, state, empty, purview_mask, Direction.CAUSE), purview
			),
			entry["unconstrained_cause"],
			atol=1e-9,
			err_msg=f"unconstrained cause over {purview}",
		)
		np.testing.assert_allclose(
			purview_marginal(
				repertoire(factors, state, empty, purview_mask, Direction.EFFECT), purview
			),
			entry["unconstrained_effect"],
			atol=1e-9,
			err_msg=f"unconstrained effect over {purview}",
		)
		for row in entry["by_mechanism"]:
			mechanism_mask = (
				jnp.zeros(system.n, dtype=bool).at[jnp.asarray(row["mechanism"])].set(True)
			)
			for direction, field in (
				(Direction.CAUSE, "cause_repertoire"),
				(Direction.EFFECT, "effect_repertoire"),
			):
				np.testing.assert_allclose(
					purview_marginal(
						repertoire(factors, state, mechanism_mask, purview_mask, direction),
						purview,
					),
					row[field],
					atol=1e-9,
					err_msg=f"{direction} of {row['mechanism']} over {purview}",
				)


def test_fixture_provenance() -> None:
	"""Test that every fixture records the pinned oracle ref and conventions."""
	for path in FIXTURES.rglob("*.json"):
		fixture = json.loads(path.read_text())
		assert fixture["oracle"]["ref"].startswith("ce2b2832"), path
		assert "little-endian" in fixture["conventions"]["state_indexing"], path


def test_subsets_alignment() -> None:
	"""Test that fixtures' unit indexing matches the canonical subset table width."""
	fixture = load("iit4", "basic")
	assert subsets(fixture["network"]["n_units"]).shape[1] == fixture["network"]["n_units"]
